# Generated by Django 6.0 on 2025-12-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_curso_materia_alter_estudiantes_curso_cursomateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='materias',
        ),
    ]
